spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true
    user:
      name: cursoms-eureka-user
      password: ue-serrr-csskoameuu

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
